### ISSUE TITLE
Developer's forum: no posts appear, no guide menu appears.

### ISSUE THREAD

**Issue by thanelmas** [MichalPaszkiewicz/inknote#13]
![screenshot](https://cloud.githubusercontent.com/assets/10010156/9980539/2203acc8-5fa6-11e5-875a-307f5297f4a3.png)

**Comment by MichalPaszkiewicz** [comment]
The developer forum server is currently hosted with a free licence on heroku, which means that the application goes to sleep if noone accesses is within 24 hours and can then take a while to load next time someone requests it. 

If this project gets some funding, I will of course upgrade it.
