### ISSUE TITLE
disable adding notes with lengths that invalidate the time signature

### ISSUE THREAD

**Issue by JDongian** [MichalPaszkiewicz/inknote#23]
![a](https://cloud.githubusercontent.com/assets/3201248/14069669/8cf7f70e-f462-11e5-9624-5765d4b2bb35.png)

**Comment by MichalPaszkiewicz** [comment]
This is now optional. Please go to menu -> tools -> settings, there you can turn "allow bar overflow" on or off to suit your needs.

Thanks for your contribution :)
